name = "Skyward Industry"
author = "Brady"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
	file = "index.toml"
	hash-format = "sha256"
	hash = "7f9547720e9fc53d687ffcde53b2742b64f1b94e3c9f90377e87bb37f4c7970b"

[versions]
	minecraft = "1.21.1"
	neoforge = "21.1.233"
