name = "Skyward Industry"
author = "Brady"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
	file = "index.toml"
	hash-format = "sha256"
	hash = "3d29dbb90b3b0c1b62800913b933007d3823cbe0e5418d372eba638c6d9fcf02"

[versions]
	minecraft = "1.21.1"
	neoforge = "21.1.233"
