name = "Skyward Industry"
author = "Brady"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
	file = "index.toml"
	hash-format = "sha256"
	hash = "63aa589a004af83ad9499113ad2078dfda36beb35e2253d937dc46ac6dffc66e"

[versions]
	minecraft = "1.21.1"
	neoforge = "21.1.233"
